# Version of plugin, dont change them, it need to updates.
version: 2.0

messages:
    # Enable message that thrown when player try avoid protection or dont have permission.
    enabled: true
    prefix: §6[CarryOnAnimals]
    # Message if player dont have carryonanimals.default permission
    permission: §cYou cant do this!
    # Message if player try to pickup entity that is not in allowed entities list. Empty string - dont send any message
    invalidEntity: ''
    reload: §aPlugin was reloaded!
    protections: '§eEnabled protections: §a'
    notEnabledWorld: §cThis world is not enabled!
    help: |-
        §aHelp:
        §e/carryonanimals help - §fShow help
        §e/carryonanimals reload - §fReload plugin
        §e/carryonanimals protections - §fShow enabled protections

# Protections list
protections:
    # Enable or disable all protections
    enabled: true
    # Towny plugin
    towny:
        enabled: true
        # Message when player trying to avoid protection
        message: §cYou cant do this!
        # Allow allies to carry on animals
        allowAlliance: false
        # Allow players where in one nation with you to carry on animals
        allowNation: false
        # Only king can carry on animals (Work only if allowNation is enabled)
        onlyKing: false
    # WorldGuard plugin [Experimental]
    worldguard:
        enabled: false
        # Message when player trying to avoid protection
        message: §cYou cant do this!

allowedEntities:
    - Sheep
    - Chicken
    - Cow
    - Pig
    - Wolf

sounds:
    onPickUp:
        enabled: true
        name: BLOCK_ANVIL_BREAK
        volume: 4
        pitch: 0.5
    onPlace:
        enabled: true
        name: BLOCK_ANVIL_FALL
        volume: 4
        pitch: 0.5

particles:
    enabled: true
    type: Cloud
    count: 10

# Worlds names where plugin will work
worlds:
    - world
