main: org.kalbinvv.carryon.CarryOn
name: CarryOnAnimals
version: '1.3'
api-version: 1.16
description: Adds the ability to move animals on the head.
softdepend: [Towny, WorldGuard, bStats]
commands:
    carryonanimals:
        description: Main plugin command.
        usage: /carryonanimals
        aliases: [coa]
